.TH "file.h" 3 "Сб 30 Май 2020" "РГЗ" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <regex>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <list>\fP
.br
\fC#include <set>\fP
.br
\fC#include <map>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBoptions\fP"
.br
.ti -1c
.RI "class \fBfile\fP"
.br
.ti -1c
.RI "class \fBexecutable_file\fP"
.br
.ti -1c
.RI "class \fBnon_executable_file\fP"
.br
.in -1c
.SS "Макросы"

.in +1c
.ti -1c
.RI "#define \fB_CRT_SECURE_NO_WARNINGS\fP"
.br
.in -1c
.SS "Определения типов"

.in +1c
.ti -1c
.RI "typedef size_t \fBsize_t_t\fP"
.br
.in -1c
.SS "Функции"

.in +1c
.ti -1c
.RI "bool \fBcheck_str\fP (const std::string &str)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBfile\fP &f1, const \fBfile\fP &f2)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBfile\fP &f1, const \fBfile\fP &f2)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBexecutable_file\fP &f1, const \fBexecutable_file\fP &f2)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBexecutable_file\fP &f1, const \fBexecutable_file\fP &f2)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBnon_executable_file\fP &f1, const \fBnon_executable_file\fP &f2)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBnon_executable_file\fP &f1, const \fBnon_executable_file\fP &f2)"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBfile\fP &f1, const \fBfile\fP &f2)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBfile\fP &f1, const \fBfile\fP &f2)"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBexecutable_file\fP &f1, const \fBexecutable_file\fP &f2)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBexecutable_file\fP &f1, const \fBexecutable_file\fP &f2)"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBnon_executable_file\fP &f1, const \fBnon_executable_file\fP &f2)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBnon_executable_file\fP &f1, const \fBnon_executable_file\fP &f2)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBexecutable_file\fP &f)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBnon_executable_file\fP &f)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &is, \fBexecutable_file\fP &f)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &is, \fBnon_executable_file\fP &f)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBfile\fP &f)"
.br
.in -1c
.SH "Макросы"
.PP 
.SS "#define _CRT_SECURE_NO_WARNINGS"

.SH "Типы"
.PP 
.SS "typedef size_t \fBsize_t_t\fP"

.SH "Функции"
.PP 
.SS "bool check_str (const std::string & str)"

.SS "bool operator!= (const \fBexecutable_file\fP & f1, const \fBexecutable_file\fP & f2)"

.SS "bool operator!= (const \fBfile\fP & f1, const \fBfile\fP & f2)"

.SS "bool operator!= (const \fBnon_executable_file\fP & f1, const \fBnon_executable_file\fP & f2)"

.SS "bool operator< (const \fBexecutable_file\fP & f1, const \fBexecutable_file\fP & f2)"

.SS "bool operator< (const \fBfile\fP & f1, const \fBfile\fP & f2)"

.SS "bool operator< (const \fBnon_executable_file\fP & f1, const \fBnon_executable_file\fP & f2)"

.SS "std::ostream& operator<< (std::ostream & os, const \fBexecutable_file\fP & f)"

.SS "std::ostream& operator<< (std::ostream & os, const \fBfile\fP & f)"

.SS "std::ostream& operator<< (std::ostream & os, const \fBnon_executable_file\fP & f)"

.SS "bool operator== (const \fBexecutable_file\fP & f1, const \fBexecutable_file\fP & f2)"

.SS "bool operator== (const \fBfile\fP & f1, const \fBfile\fP & f2)"

.SS "bool operator== (const \fBnon_executable_file\fP & f1, const \fBnon_executable_file\fP & f2)"

.SS "bool operator> (const \fBexecutable_file\fP & f1, const \fBexecutable_file\fP & f2)"

.SS "bool operator> (const \fBfile\fP & f1, const \fBfile\fP & f2)"

.SS "bool operator> (const \fBnon_executable_file\fP & f1, const \fBnon_executable_file\fP & f2)"

.SS "std::istream& operator>> (std::istream & is, \fBexecutable_file\fP & f)"

.SS "std::istream& operator>> (std::istream & is, \fBnon_executable_file\fP & f)"

.SH "Автор"
.PP 
Автоматически создано Doxygen для РГЗ из исходного текста\&.
