.TH "РГЗ.cpp" 3 "Сб 30 Май 2020" "РГЗ" \" -*- nroff -*-
.ad l
.nh
.SH NAME
РГЗ.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'menu\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Макросы"

.in +1c
.ti -1c
.RI "#define \fB_CRTDBG_MAP_ALLOC\fP"
.br
.in -1c
.SS "Функции"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Макросы"
.PP 
.SS "#define _CRTDBG_MAP_ALLOC"

.SH "Функции"
.PP 
.SS "int main ()"

.SH "Автор"
.PP 
Автоматически создано Doxygen для РГЗ из исходного текста\&.
